### ISSUE TITLE
Homepage Mockup Design

### ISSUE THREAD

**Issue by cwpeng** [Padax/w-components-website#3]
Refer to issue in w-components project:
https://github.com/Padax/w-components/issues/100

**Comment by yakkowu** [comment]
# UPDATE

According to @nizniz187 ’s feedback, add Measurements to the mockup. With viewing permission, you can measure the distance between the components and the grids.

⤷ Here's the currently file [in Figma](https://www.figma.com/file/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=121%3A91).

![image](https://user-images.githubusercontent.com/46119829/143280899-89ca940e-f3c6-4832-b083-0f379526db94.png)

https://user-images.githubusercontent.com/46119829/143281422-4148569b-817f-4fcf-beeb-02bb90a8c299.mov
